#!/usr/bin/sh

# Script to download updated GSF APK's from GrapheneOS's repo

if [ -n "$1" ]; then dl=$1
else dl=true
fi
lastup=$(cat ./lastup.txt || echo '' && touch ./lastup.txt)
url='https://apps.grapheneos.org/packages/com.google.android.gsf/31/'
apkdate=$(
  curl $url \
    | cat \
    | grep -o "[0-9][0-9][0-9][0-9]-[A-Z][a-z][a-z]-[0-9][0-9]" \
    | cat
)

if [ "$lastup" = "$apkdate" ]; then
  termux-toast "Google Services Framework is up-to-date." 
else
  echo $apkdate > ./lastup.txt

  if [ $dl ]; then
    termux-toast "New version of Google Services Framework is available. Install from the Downloads folder." 
    curl "$url/base.apk" --output base.apk
    mv base.apk ~/storage/downloads
  else
    termux-toast "New version of Google Services Framework is available." 
  fi

fi

exit 0

